import sys
from pathlib import Path
from dotenv import load_dotenv
sys.path.insert(0, str(Path(__file__).parent.parent))
from src.graph import build_graph


import json
rubric_path = Path(__file__).parent.parent / "src" / "resources" / "rubric.json"
with open(rubric_path, "r", encoding="utf-8") as f:
    rubric = json.load(f)
load_dotenv()

graph = build_graph()
initial_state = {
    "task_description": "Audit this repository against the provided report.",
    "repository_path": "https://github.com/ermiyas111/10Acweek2",
    "audit_report_text": "",
    "pdf_path": "C:\\Users\\HP\\Downloads\\final_report.pdf",
    "evidence": [],
    "audit_summary": {},
    "final_verdict": "",
    "rubric": rubric,
}


result = graph.invoke(
    initial_state,
    config={"run_name": "automaton-auditor-test", "tags": ["langsmith", "test"]},
)

# Generate Peer Audit Markdown report
import datetime
rubric = result.get("rubric", {})
opinions_raw = result.get("judicial_opinions", [])
errors = result.get("errors", [])

def _status_from_score(final_score: float) -> str:
    if final_score >= 4.0:
        return "Pass"
    if final_score >= 2.5:
        return "Needs Improvement"
    return "Fail"

if not rubric or "dimensions" not in rubric:
    markdown_report = "# Peer Audit Report\n\nRubric missing or invalid."
else:
    persona_map = {}
    for op in opinions_raw:
        persona = op.get("persona", "Unknown")
        persona_map[persona.lower()] = op

    criterion_breakdown = []
    criterion_scores = []
    for dim in rubric["dimensions"]:
        crit_name = dim.get("name", "Unnamed Criterion")
        judge_opinions = []
        scores = []
        for persona in ["prosecutor", "defense", "techlead"]:
            op = persona_map.get(persona.lower())
            if op:
                score = op.get("score", 1)
                rationale = op.get("rationale", "No rationale provided.")
                judge_opinions.append(f"- {persona.title()} (Score: {score}): {rationale}")
                scores.append(score)
        final_score = round(sum(scores) / len(scores), 2) if scores else 1.0
        criterion_scores.append((crit_name, final_score))
        remediation_emoji = "✅" if final_score >= 4 else "⚠️"
        criterion_breakdown.append(
            f"### {crit_name}\nFinal Score: **{final_score}**\n\n" +
            "\n".join(judge_opinions) +
            f"\n\nRemediation: {remediation_emoji}"
        )

    overall_score = round(sum(s for _, s in criterion_scores) / len(criterion_scores), 2) if criterion_scores else 1.0
    status = _status_from_score(overall_score)
    summary = f"Overall Score: **{overall_score} / 5.00**\nStatus: **{status}**\n"

    sorted_criteria = sorted(criterion_scores, key=lambda x: x[1])
    remediation_plan = [f"{i+1}. {name} (Score: {score})" for i, (name, score) in enumerate(sorted_criteria)]

    version = rubric.get("rubric_metadata", {}).get("version", "vX.X.X")
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    methodology = "This report was generated by Automaton Auditor Swarm using a rubric-driven, multi-judge peer review process. Each criterion is scored independently by specialized agents, and the Chief Justice synthesizes the results for actionable feedback."

    markdown_report = (
        "# Peer Audit Report\n\n"
        f"## Executive Summary\n{summary}\n"
        f"## Criterion Breakdown\n\n" +
        "\n\n".join(criterion_breakdown) +
        "\n\n## Prioritized Remediation Plan\n" +
        "\n".join(remediation_plan) +
        f"\n\n---\n\n_Automaton Auditor Swarm {version} — {timestamp}_\n\n{methodology}\n"
    )

# print(markdown_report)
with open("peer_audit_report.md", "w", encoding="utf-8") as f:
    f.write(markdown_report)
if errors:
    print("Errors:", errors)